@Compound_V_API_HostAddress = http://localhost:5050

GET {{Compound_V_API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Compound_V_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Password1!"
}

###

POST {{Compound_V_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Password1!"
}

###

POST {{Compound_V_API_HostAddress}}/api/identity/userRole
Content-Type: application/json

{
    "userEmail": "test@test.com",
    "roleName": "Owner"
}


###

POST {{Compound_V_API_HostAddress}}/api/identity/UnAssignUserRole
Content-Type: application/json

{
    "userEmail": "test@test.com",
    "roleName": "newOwner1"
}

###

POST {{Compound_V_API_HostAddress}}/api/identity/createRole
Content-Type: application/json

{
    "Name": "Chef"
}

###
DELETE {{Compound_V_API_HostAddress}}/api/identity/deleteRole
Content-Type: application/json

{
    "Name": "Chef"
}

###

PATCH {{Compound_V_API_HostAddress}}/api/identity/updateRole
Content-Type: application/json

{
    "Id" : "3ca6b7fc-6217-49ed-9496-8b18d6d49b05",
    "Name": "newOwner1"
}

###

POST {{Compound_V_API_HostAddress}}/api/identity/createUser
Content-Type: application/json

{
    "Email": "test5@test.com",
    "Name" : "test5",
    "password" : "test5123!@#S"

}
  
