@Compound_V_API_HostAddress = http://localhost:5050

GET {{Compound_V_API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Compound_V_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Password1!"
}

###

POST {{Compound_V_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Password1!"
}

###

POST {{Compound_V_API_HostAddress}}/api/identity/userRole
Content-Type: application/json

{
    "userEmail": "test@test.com",
    "roleName": "Owner"
}


###

POST {{Compound_V_API_HostAddress}}/api/identity/createRole
Content-Type: application/json

{
    "Name": "Chef"
}